### ISSUE TITLE
Master分支突然各种报错了，npm哪个版本的呀？

### ISSUE THREAD

**Issue by xzqqqcom** [mobaijun8/hexo_blog_matery#13]
ERROR /www/wwwroot/myblog/themes/matery/layout/layout.ejs:69
    67| 
    68| 
 >> 69| <% if (theme.clicklove.enable) { %>
    70|     <script src="<%- theme.libs.js.clicklove %>" async="async"></script>
    71| <% } %>
    72| 

Cannot read properties of undefined (reading 'enable')

**Comment by mobaijun** [comment]
GitHub仓库有一段时间没有更新了，可以去码云拉取最新代码，https://gitee.com/mobaijun/mobai_hexoBlog/tree/master/
